import { Module } from '@nestjs/common';
import { _TRAZAESTADISTICASYSTEMACHEMA, _TRAZANEGOCIOSYSTEMACHEMA, _TRAZAPAGOSYSTEMACHEMA, _TRAZARUTASYSTEMACHEMA } from './schemas/index.schema';

@Module({
    imports:
    [
        _TRAZANEGOCIOSYSTEMACHEMA,
        _TRAZAESTADISTICASYSTEMACHEMA,
        _TRAZAPAGOSYSTEMACHEMA,
        _TRAZARUTASYSTEMACHEMA
    ],
    exports:
    [
        _TRAZANEGOCIOSYSTEMACHEMA,
        _TRAZAESTADISTICASYSTEMACHEMA,
        _TRAZAPAGOSYSTEMACHEMA,
        _TRAZARUTASYSTEMACHEMA
    ]
})
export class Estadisticas_ModelsModule {}
