export enum RoleType {
  ADMIN_ROLE = 'ADMIN_ROLE',
  CONTRATISTA_ROLE = 'CONTRATISTA_ROLE',
  ARTIST_ROLE = 'ARTIST_ROLE',
}



export enum artistSubRole {
  CANTANTE_ROLE = 'CANTANTE_ROLE',
  INSTRUMENTISTA_ROLE = 'INSTRUMENTISTA_ROLE',
  ESCENADIRECTOR_ROLE = 'ESCENADIRECTOR_ROLE',
  ORQUESTADIRECTOR_ROLE = 'ORQUESTADIRECTOR_ROLE'
}



